version: '3.8'
services: 
  postgresDB:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=monolitoDB
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5436:5432"